#!/usr/bin/env bash
# PR gate for the technique catalog in skills/solidity-gas-optimizer/catalog/.
# Checks that every card is well-formed:
#   - card IDs are unique across all category files
#   - every category file is registered in the prefix map below
#   - every card ID carries its file's prefix (ST- in storage.md, EXE- in execution.md, ...)
#   - every card body has all eight schema fields: Kind, Detect, Hint,
#     Transform, Savings, Preconditions, Risks, Source
#   - INDEX.md is current (regenerated by build-index.sh and diffed)
# It does not cross-check SOURCES.md mappings against the cards.
# Prints per-file card counts; exits nonzero on any violation. Run from anywhere.
set -uo pipefail
dir="$(cd "$(dirname "$0")/../../solidity-gas-optimizer/catalog" && pwd)"
fail=0

declare -A prefixes=(
  [storage.md]=ST
  [deployment.md]=DEP
  [external-calls.md]=XC
  [architecture.md]=ARC
  [calldata.md]=CD
  [assembly.md]=ASM
  [execution.md]=EXE
  [forbidden.md]=FBD
)

dups=$(grep -h '^## ' "$dir"/*.md 2>/dev/null | awk '{print $2}' | sort | uniq -d)
if [ -n "$dups" ]; then
  echo "FAIL duplicate card IDs:"
  echo "$dups"
  fail=1
fi

for f in "$dir"/*.md; do
  name=$(basename "$f")
  case "$name" in INDEX.md|SOURCES.md) continue ;; esac
  prefix="${prefixes[$name]:-}"
  if [ -z "$prefix" ]; then
    echo "FAIL unknown reference file $name (add it to the prefix map in this script)"
    fail=1
    continue
  fi

  count=$(grep -c '^## ' "$f" || true)
  echo "$name: $count cards"

  bad=$(grep '^## ' "$f" | grep -v "^## $prefix-" || true)
  if [ -n "$bad" ]; then
    echo "FAIL wrong ID prefix in $name (expected $prefix-):"
    echo "$bad"
    fail=1
  fi

  awk -v file="$name" '
    function check(   n, req, i) {
      n = split("**Kind**,**Detect**,**Hint**,**Transform**,**Savings**,**Preconditions**,**Risks**,**Source**", req, ",")
      for (i = 1; i <= n; i++)
        if (index(body, req[i]) == 0) { printf "FAIL %s %s missing field %s\n", file, id, req[i]; bad = 1 }
    }
    /^## / { if (id != "") check(); id = $2; body = ""; next }
    { body = body $0 "\n" }
    END { if (id != "") check(); exit bad }
  ' "$f" || fail=1
done

"$(dirname "$0")/build-index.sh" --check || fail=1

if [ "$fail" -eq 0 ]; then
  echo "OK all reference cards valid"
else
  exit 1
fi
